#!/bin/bash
#assume we're in the project dir
project_dir=.
#assume we don't have a specific build folder
build_dir=$project_dir

sources="$(find $project_dir/src | grep .java)"

for file in $sources; do
    command echo "Compiling: $file";
done

command rm -rf "$build_dir/classes"
command mkdir "$build_dir/classes"
command echo "$sources" > "$build_dir/sources.txt"
command javac -d "$build_dir/classes" -cp "$build_dir/src/jgrader/jar/*" "@$build_dir/sources.txt"
command rm "$build_dir/sources.txt"
